from exporter.types import Header, HeaderFieldType


AIRCRAFT_TABLE_HEADERS = [
    Header(name="AircraftID", field_type=HeaderFieldType.TEXT),
    Header(name="EquipmentType", field_type=HeaderFieldType.TEXT),
    Header(name="TypeCode", field_type=HeaderFieldType.TEXT),
    Header(name="Year", field_type=HeaderFieldType.YEAR),
    Header(name="Make", field_type=HeaderFieldType.TEXT),
    Header(name="Model", field_type=HeaderFieldType.TEXT),
    Header(name="Category", field_type=HeaderFieldType.TEXT),
    Header(name="Class", field_type=HeaderFieldType.TEXT),
    Header(name="GearType", field_type=HeaderFieldType.TEXT),
    Header(name="EngineType", field_type=HeaderFieldType.TEXT),
    Header(name="Complex", field_type=HeaderFieldType.BOOLEAN),
    Header(name="HighPerformance", field_type=HeaderFieldType.BOOLEAN),
    Header(name="Pressurized", field_type=HeaderFieldType.BOOLEAN),
    Header(name="TAA", field_type=HeaderFieldType.BOOLEAN),
]

FLIGHT_TABLE_HEADERS = [
    Header(name="Date", field_type=HeaderFieldType.DATE),
    Header(name="AircraftID", field_type=HeaderFieldType.TEXT),
    Header(name="From", field_type=HeaderFieldType.TEXT),
    Header(name="To", field_type=HeaderFieldType.TEXT),
    Header(name="Route", field_type=HeaderFieldType.TEXT),
    Header(name="TimeOut", field_type=HeaderFieldType.TIME),
    Header(name="TimeOff", field_type=HeaderFieldType.TIME),
    Header(name="TimeOn", field_type=HeaderFieldType.TIME),
    Header(name="TimeIn", field_type=HeaderFieldType.TIME),
    Header(name="OnDuty", field_type=HeaderFieldType.TIME),
    Header(name="OffDuty", field_type=HeaderFieldType.TIME),
    Header(name="TotalTime", field_type=HeaderFieldType.DECIMAL),
    Header(name="PIC", field_type=HeaderFieldType.DECIMAL),
    Header(name="SIC", field_type=HeaderFieldType.DECIMAL),
    Header(name="Night", field_type=HeaderFieldType.DECIMAL),
    Header(name="Solo", field_type=HeaderFieldType.DECIMAL),
    Header(name="CrossCountry", field_type=HeaderFieldType.DECIMAL),
    Header(name="NVG", field_type=HeaderFieldType.DECIMAL),
    Header(name="NVGOps", field_type=HeaderFieldType.DECIMAL),
    Header(name="Distance", field_type=HeaderFieldType.DECIMAL),
    Header(name="DayTakeoffs", field_type=HeaderFieldType.NUMBER),
    Header(name="DayLandingsFullStop", field_type=HeaderFieldType.NUMBER),
    Header(name="NightTakeoffs", field_type=HeaderFieldType.NUMBER),
    Header(name="NightLandingsFullStop", field_type=HeaderFieldType.NUMBER),
    Header(name="AllLandings", field_type=HeaderFieldType.NUMBER),
    Header(name="ActualInstrument", field_type=HeaderFieldType.DECIMAL),
    Header(name="SimulatedInstrument", field_type=HeaderFieldType.DECIMAL),
    Header(name="HobbsStart", field_type=HeaderFieldType.DECIMAL),
    Header(name="HobbsEnd", field_type=HeaderFieldType.DECIMAL),
    Header(name="TachStart", field_type=HeaderFieldType.DECIMAL),
    Header(name="TachEnd", field_type=HeaderFieldType.DECIMAL),
    Header(name="Holds", field_type=HeaderFieldType.NUMBER),
    Header(
        name="Approach1",
        field_type=HeaderFieldType.PACKED_DETAIL,
        comment="#;type;runway;airport;comments",
    ),
    Header(name="Approach2", field_type=HeaderFieldType.PACKED_DETAIL),
    Header(name="Approach3", field_type=HeaderFieldType.PACKED_DETAIL),
    Header(name="Approach4", field_type=HeaderFieldType.PACKED_DETAIL),
    Header(name="Approach5", field_type=HeaderFieldType.PACKED_DETAIL),
    Header(name="Approach6", field_type=HeaderFieldType.PACKED_DETAIL),
    Header(name="DualGiven", field_type=HeaderFieldType.DECIMAL),
    Header(name="DualReceived", field_type=HeaderFieldType.DECIMAL),
    Header(name="SimulatedFlight", field_type=HeaderFieldType.DECIMAL),
    Header(name="GroundTraining", field_type=HeaderFieldType.DECIMAL),
    Header(name="InstructorName", field_type=HeaderFieldType.TEXT),
    Header(name="InstructorComments", field_type=HeaderFieldType.TEXT),
    Header(
        name="Person1",
        field_type=HeaderFieldType.PACKED_DETAIL,
        comment="name;role;email",
    ),
    Header(name="Person2", field_type=HeaderFieldType.PACKED_DETAIL),
    Header(name="Person3", field_type=HeaderFieldType.PACKED_DETAIL),
    Header(name="Person4", field_type=HeaderFieldType.PACKED_DETAIL),
    Header(name="Person5", field_type=HeaderFieldType.PACKED_DETAIL),
    Header(name="Person6", field_type=HeaderFieldType.PACKED_DETAIL),
    Header(name="FlightReview", field_type=HeaderFieldType.BOOLEAN),
    Header(name="Checkride", field_type=HeaderFieldType.BOOLEAN),
    Header(name="IPC", field_type=HeaderFieldType.BOOLEAN),
    Header(name="NVGProficiency", field_type=HeaderFieldType.BOOLEAN),
    Header(name="FAA6158", field_type=HeaderFieldType.BOOLEAN),
    Header(name="[Text]CustomFieldName", field_type=HeaderFieldType.TEXT),
    Header(name="[Numeric]CustomFieldName", field_type=HeaderFieldType.DECIMAL),
    Header(name="[Hours]CustomFieldName", field_type=HeaderFieldType.DECIMAL),
    Header(name="[Counter]CustomFieldName", field_type=HeaderFieldType.NUMBER),
    Header(name="[Date]CustomFieldName", field_type=HeaderFieldType.DATE),
    Header(name="[DateTime]CustomFieldName", field_type=HeaderFieldType.DATE_TIME),
    Header(name="[Toggle]CustomFieldName", field_type=HeaderFieldType.BOOLEAN),
    Header(name="PilotComments", field_type=HeaderFieldType.TEXT),
]
